version: '3.8'
services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
#      Hardcoded port
      - "5432:5432"
    networks:
      - microservice-network
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_CONFIG_PORT:-8000}:8000"
    environment:
      PYTHONPATH: /app
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

      POSTGRES_DEBUG: ${POSTGRES_DEBUG:-0}
      POSTGRES_POOL_SIZE: ${POSTGRES_POOL_SIZE:-5}
      POSTGRES_MAX_OVERFLOW: ${POSTGRES_MAX_OVERFLOW:-10}

      APP_RUN_HOST: ${APP_RUN_HOST:-0.0.0.0}
      APP_RUN_PORT: ${APP_RUN_PORT:-8000}
      DEBUG: ${DEBUG:-0}

      TOKEN_EXPIRATION_MINUTES: ${TOKEN_EXPIRATION_MINUTES:-30}
      # TODO: unused now
      TOKEN_EXPIRATION_DAYS: ${TOKEN_EXPIRATION_DAYS:-30}

    command: /app/start.sh
    depends_on:
      - pg
    networks:
      - microservice-network
#    volumes:
#      - .:/app

# TODO: WARNING: pgadmin only for dev, not for prod
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - pg
    networks:
      - microservice-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  microservice-network:
    external: false
    driver: bridge

volumes:
  pg_data:
  pgadmin_data: